### ISSUE TITLE
Preference initPoint is null after setting expiration date.

### ISSUE THREAD

**Issue by tmacudzinski** [mercadopago/dx-java#56]
**Description**
I am trying to set expiration date of the payment preference, but this cause to receive preference with null in initPoint in response.

**To Reproduce**

Here is the code which generates this problem:

```
        MercadoPago.SDK.setClientId(CLIENT_ID);
        MercadoPago.SDK.setClientSecret(CLIENT_SECRET);

        Preference preference = new Preference();
        Date today = DateFormat.getDateInstance(DateFormat.LONG, new Locale("es", "AR")).getCalendar().getTime();
        Calendar c = Calendar.getInstance();
        c.setTime(today);
        c.add(Calendar.HOUR_OF_DAY, -24);
        Date yesterday = c.getTime();

        c.add(Calendar.HOUR_OF_DAY, 48);
        Date tomorrow = c.getTime();

        preference.setExpires(true);
        preference.setExpirationDateFrom(yesterday);
        preference.setExpirationDateTo(tomorrow);

        Item item1 = new Item();
        item1.setId("1")
                .setTitle("new item")
                .setCurrencyId("ARS")
                .setQuantity(2)
                .setUnitPrice(0.5f);

        ArrayList<Item> items = new ArrayList<Item>();
        items.add(item1);
        preference.setItems(items);

        Payer payer = new Payer();
        preference.setPayer(payer);

        Preference received = preference.save();

        String generatedLink = received.getInitPoint();
```

When I comment this part of the code:

```
        preference.setExpires(true);
        preference.setExpirationDateFrom(yesterday);
        preference.setExpirationDateTo(tomorrow);
```

everything starts to work fine.

**Expected behavior**
Correctly get initPoint (not null) from received in response Preference, when expiration date is set

**Comment by joelibaceta** [comment]
Probably solved in **1.0.23**

**Comment by jirungaray** [comment]
problem persists, the problem is we can get feedback from the API on the fields, is there some way we can log req/responses for the SDK?

**Comment by delias-silva** [comment]
In newer versions the problem does not occur.
